#baseURL = "https://sslarch.github.io/"
baseURL = "http://joeroe.io/sslarch.github.io/"
languageCode = "en"
title = "CAA SSLA"
subtitle = 'CAA International Special Interest Group "Scientific Scripting Languages in Archaeology"'
theme = "terminal"

# Main menu
sectionPagesMenu = "main"

[params.logo]
  logoText = "CAA/SSLA"
  logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  #showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

# Twitter cards
[params.twitter]
  creator = "CAA_SSLA"
  site = "CAA_SSLA"

# Localised text
[languages]
  [languages.en]
    languageName = "English"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"


